import { Container } from '@mui/system'
import Head from 'next/head'
import FormMain from '../src/components/Forms/FormMain'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Container>
          <FormMain />
        </Container>
      </main>

      <footer>
        <a
          href="https://lboarro.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Desenvolvido por Lara Boarro
        </a>
      </footer>
    </div>
  )
}
